Update to Rails 5.0 and add extracted rails-controller-testing gem:
> BlogTest#test_Blog_post_should_be_rendered:
> NoMethodError: assert_template has been extracted to a gem. To continue
> using it, add `gem 'rails-controller-testing'` to your Gemfile.