Comment out dumper_enabled_host? because of
NoMethodError: undefined method `dumper_enabled_host?' for main:Object
https://github.com/coderdojo-japan/coderdojo.jp/pull/326/files#r186308427
in Running: rake assets:precompile to deploy to Heroku.